- hosts: pool
  gather_facts: no

  vars:
    pool_prefix: persistent_node

  tasks:
  - name: Save journalctl log
    shell: "journalctl > /tmp/jctl"

  - name: Compress journalctl log
    shell: "xz -f /tmp/jctl"

  - name: Fetch journalctl log
    fetch:
      src: "/tmp/jctl.xz"
      dest: "/tmp/logs/jctl/{{ inventory_hostname }}.jctl.xz"
      flat: yes

  - name: Delete journalctl log
    file:
      path: "/tmp/jctl.xz"
      state: absent

  - name: Fetch node info
    synchronize:
      src: /var/lib/indy/sandbox/node*.json
      dest: /tmp/logs/node_info
      mode: pull
    ignore_errors: yes

  - name: Fetch node logs
    synchronize:
      src: /var/log/indy/sandbox/
      dest: /tmp/logs
      mode: pull
    ignore_errors: yes
    become: yes

  - name: Stop service
    service: name=indy-node state=stopped
    become: yes

  - name: Compress metrics db
    shell: "tar cJvf /tmp/metrics_db.tar.xz /var/lib/indy/sandbox/data/{{ inventory_hostname|replace(pool_prefix,'Node') }}/metrics_db"
    ignore_errors: yes

  - name: Fetch metrics db
    fetch:
      src: "/tmp/metrics_db.tar.xz"
      dest: "/tmp/logs/metrics/metrics_db{{ inventory_hostname|replace(pool_prefix,'') }}.tar.xz"
      flat: yes
    ignore_errors: yes

  - name: Delete metrics db
    file:
      path: "/tmp/metrics_db.tar.xz"
      state: absent

#  - name: Process metrics
#    shell: "cd /usr/local/bin && python3 get_metrics --data_dir /var/lib/indy/sandbox/data/{{ inventory_hostname|replace(pool_prefix,'Node') }}/metrics_db --output /home/ubuntu/metrics{{ inventory_hostname|replace(pool_prefix,'') }}.csv > /home/ubuntu/metrics_summary{{ inventory_hostname|replace(pool_prefix,'') }}.txt"
#    become: yes
#
#  - name: Fetch metrics
#    fetch:
#      src: "/home/ubuntu/metrics{{ inventory_hostname|replace(pool_prefix,'') }}.csv"
#      dest: "/tmp/logs/metrics/metrics{{ inventory_hostname|replace(pool_prefix,'') }}.csv"
#      flat: yes
#
#  - name: Fetch metrics summary
#    fetch:
#      src: "/home/ubuntu/metrics_summary{{ inventory_hostname|replace(pool_prefix,'') }}.txt"
#      dest: "/tmp/logs/metrics/metrics_summary{{ inventory_hostname|replace(pool_prefix,'') }}.txt"
#      flat: yes

  - name: Start service
    service: name=indy-node state=started
    become: yes
